### ISSUE TITLE
Make grabber code

### ISSUE THREAD

**Issue by 12sliu** [Brighton-FTC/2024#6]
This is just making a simple grabber like last time. Shouldn't be that hard, use last year's grabber as a example and we should be fine.

**Comment by sbottingota** [comment]
Made a very basic implementation of the grabber code. Code is a bit sloppy, but I'll work on it tomorrow.  
https://github.com/Brighton-FTC/2024/commit/943b61b352d12679ea17121939ff985aac3f246a

**Comment by 12sliu** [comment]
Best to follow FTCLib example, I suppose. 

By the way, you do have tests this week, maybe consider taking a break from robotics to study? Engineers haven't done anything we can test on, so we won't test anything we write; there's time pressure, but it's not THAT urgent. I'm swamped with tests (8 in the next 7 days), so I also won't be able to work too much on the code; I won't think less of you if you don't complete your issue as fast as possible within these few days.

**Comment by sbottingota** [comment]
https://github.com/Brighton-FTC/2024/commit/79e4caa8020a858b1e11e0bf40dfef572942a322  
Ok I implemented the `SimpleServo` thing.

**Comment by sbottingota** [comment]
@12sliu, do we know what the servo names are?

**Comment by sbottingota** [comment]
Also, how do we find angle the servos need to be at to open/close/tilt the grabber? I was thinking of making a separate opmode to get those values, but do you know of a better way?

<details>
<summary>The scrappy opmode I was making</summary>

```java
package org.firstinspires.ftc.teamcode.components.test;

import com.arcrobotics.ftclib.gamepad.GamepadEx;
import com.arcrobotics.ftclib.gamepad.GamepadKeys;
import com.arcrobotics.ftclib.hardware.ServoEx;
import com.arcrobotics.ftclib.hardware.SimpleServo;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;

/**
 * Some code I made to get the servo positions for the grabber. <br />
 *
 * Controls:
 * <ul>
 *     <li>Change servo - dpad left & dpad right</li>
 *     <li>Change rotation angle - dpad down & dpad up</li>
 *     <li>Rotate servo by rotation angle - A (cross on playstation) and B (circle on playstation)</li>
 * </ul>
 *
 */

@TeleOp(name = "Grabber Servo Position Tester", group = "components_test")
public class ServoPositionTester extends OpMode {
    private ServoEx[] servos;
    private int currentServoIndex = 0;

    private GamepadEx gamepad = new GamepadEx(gamepad1);

    private int rotationAngle = 20;

    @Override
    public void init() {
        servos = new ServoEx[]{
                new SimpleServo(hardwareMap, "servo_name", 0, 360),
                new SimpleServo(hardwareMap, "servo_name", 0, 360)
        };
    }

    @Override
    public void loop() {
        if (gamepad.wasJustPressed(GamepadKeys.Button.DPAD_LEFT)) {
            currentServoIndex--;
            currentServoIndex %= servos.length;
        }

        if (gamepad.wasJustPressed(GamepadKeys.Button.DPAD_RIGHT)) {
            currentServoIndex++;
            currentServoIndex %= servos.length;
        }

        if (gamepad.wasJustPressed(GamepadKeys.Button.DPAD_DOWN)) {
            rotationAngle -= 5;
        }

        if (gamepad.wasJustPressed(GamepadKeys.Button.DPAD_UP)) {
            rotationAngle += 5;
        }

        if (gamepad.wasJustPressed(GamepadKeys.Button.A)) {
            servos[currentServoIndex].rotateByAngle(rotationAngle);
        }

        if (gamepad.wasJustPressed(GamepadKeys.Button.B)) {
            servos[currentServoIndex].rotateByAngle(-rotationAngle);
        }

        telemetry.addData("Current servo index", currentServoIndex);
        telemetry.addData("Rotation angle", rotationAngle);
        telemetry.addData("Current servo angle", servos[currentServoIndex].getAngle());
    }
}
```
</details>

**Comment by 12sliu** [comment]
Pretty sure we get to name them in the software ourselves while setting things up, though I'm not entirely sure; we'll ask Oliver today

**Comment by sbottingota** [comment]
I remember there might have been some problem with `gamepad.wasJustPressed()` last year, but I can't remember. Either way, if you think it's more elegant, or there's some problem with `gamepad.wasJustPressed()`, it should be easy to change the code to bind the commands in init.

**Comment by 12sliu** [comment]
No need to change it, just leave as is.

**Comment by sbottingota** [comment]
https://github.com/Brighton-FTC/2024/commit/d267bbe28d38b214a3928da093f789c629620d1d

Made grabber into component class.

**Comment by sbottingota** [comment]
Deprecated, as we plan to use active intake instead.

**Comment by sbottingota** [comment]
Grabber is not used anymore; not sure why this is still here.
