### ISSUE TITLE
Make grabber rotating code

### ISSUE THREAD

**Issue by 12sliu** [Brighton-FTC/2024#7]
This has a slightly confusing title; the grabber is meant to rotate up and down while at the end of the arm, in a motion resembling this 

![Image](https://github.com/Brighton-FTC/2024/assets/118719719/0b923ca1-c298-4f72-b4c6-f2240937b30e)

If this isn't clear to the person who has been assigned this task, I'll explain it in person with hand motions; I am not a skilled 3D artist.

This rotating will be done with a servo.

**Comment by sbottingota** [comment]
@12sliu does the tilting thing have fixed angles it needs to point at or not?

**Comment by 12sliu** [comment]
asked engineers, waiting for response

**Comment by sbottingota** [comment]
https://github.com/Brighton-FTC/2024/commit/943b61b352d12679ea17121939ff985aac3f246a  
Made a very basic implementation of the grabber rotating code. Code is a bit sloppy, but I'll work on it tomorrow. (The code has fixed angles for the rotating thing, but it's pretty easy to change that, and I'll probably have to rewrite the whole thing someday, so ehh fine for now.)

**Comment by 12sliu** [comment]
According to Nick, the grabber is supposed to go at the angle of the canvas when the arm is moving upwards, and 90 degrees flat when not going up. 

We should probably add the grabber rotation code into the arm class. Probably goes against some kind of software architecture principle, doesn't matter. 

Do we plan on combining all the code into one giant bloated OpMode, or do we plan to use component classes with code to do specific functions (e.g. slide has a method to extend to certain length)? During the first comp of last year we did a giant OpMode, during the second comp we used component classes.

**Comment by sbottingota** [comment]
I don't really know; last year I think we combined all the components into the same class, but this year we might want to do something different if we have a lot of code.

**Comment by sbottingota** [comment]
If we used component classes during the second comp, then we should probably use those, right?

**Comment by 12sliu** [comment]
Mm, I suppose it'd be more clean too. Ok, we'll do component classes. We'll rewrite the component classes after testing and debugging them to include methods that can be called from the OpMode (after instantiating the object, just to clear up confusion).

**Comment by sbottingota** [comment]
@12sliu, would you like me to separate the grabber code and the grabber rotating code? Because at the moment I just have them [here](https://github.com/Brighton-FTC/2024/blob/grabber-code/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/test/GrabberComponent.java) in the same class.

**Comment by 12sliu** [comment]
I copied the entire thing over and removed anything related to the grabber, so no need

**Comment by sbottingota** [comment]
Ok cool.

**Comment by sbottingota** [comment]
https://github.com/Brighton-FTC/2024/commit/7c515076ba12fafa6ce901035c647e54285c6ad5

Removed grabber tilt thing from grabber code, as @12sliu is taking care of that.

**Comment by sbottingota** [comment]
Ok, turns out we're not having a grabber rotating servo.

It has been removed now.
